Create DataSource API
ca-risken/datasource-api pull request #1
Opened 2022-06-03 05:45 UTC by gassara-kys

WIP

2022-06-07 07:46 UTC, gassara-kys commented
一通りのテスト完了したのでWIP外しました

2022-06-07 11:40 UTC, gassara-kys commented
以下の単位でコミットを分割しています
- [CI周り](https://github.com/ca-risken/datasource-api/pull/1/commits/7e8f5ed1a4174502fc194f33639c51dd97abc8ee)
- [protoファイル移行](https://github.com/ca-risken/datasource-api/pull/1/commits/11e67e4b10cf07dbd2d55d967520f32105a5096b)
- package追加
  - [modelパッケージ](https://github.com/ca-risken/datasource-api/pull/1/commits/2ae4308e46b69f709ce0efc4d35c1fff88b67e00)
  - [tagパッケージ](https://github.com/ca-risken/datasource-api/pull/1/commits/4a7abdc4a054c7971e4619115af24b32da9b19cb)
  - [cryptoパッケージ](https://github.com/ca-risken/datasource-api/pull/1/commits/40d44343474456b14c76cdaef81b1a6ac4a0fc90)
  - [messageパッケージ](https://github.com/ca-risken/datasource-api/pull/1/commits/4ae89870fea0c1c544942a31f5e6c837b9f9bec6)
  - [dbパッケージ](https://github.com/ca-risken/datasource-api/pull/1/commits/767ff938433afa5d02189a94ae5679a564ff09f5)
  - [queueパッケージ](https://github.com/ca-risken/datasource-api/pull/1/commits/7eaa4386fb3016c3c34e8b606452e9dbf87fbfbf)
- gRPCサーバの実装
  - [aws](https://github.com/ca-risken/datasource-api/pull/1/commits/af6d70da34e53ceff1270d680ff6e2b0d5877e49)
  - [activity](https://github.com/ca-risken/datasource-api/pull/1/commits/94a48f63d4f58bd48d46369892f3e0285ffb6b21)
  - [google](https://github.com/ca-risken/datasource-api/pull/1/commits/af1e98813b714d3c0643b7085c41352e9e8da2f2)
  - [code](https://github.com/ca-risken/datasource-api/pull/1/commits/0671fa2d04903eb6f3c6b91d6b6f35e08bdbc6ca)
  - [osint](https://github.com/ca-risken/datasource-api/pull/1/commits/d95dcdaa2bfb5d4ba08c2fef6ace4fe5339fe691)
  - [diagnosis](https://github.com/ca-risken/datasource-api/pull/1/commits/629d5241842125899d7eb70cab574cd4290a55ff)
- その他
  - [gRPCリクエストサンプル追加](https://github.com/ca-risken/datasource-api/pull/1/commits/261b19fcfdc7691a7bfbf05cfc4ecbb6de93859a)
  - [gRPCパッケージ名（サービス名）の統一](https://github.com/ca-risken/datasource-api/pull/1/commits/2a669c896753c17e55111effce93ab919c0d58aa)
  - [ドキュメント](https://github.com/ca-risken/datasource-api/pull/1/commits/09f72c8c03904446e2ffa26a2e760a753cc4ec00)
  - [buildバッジ追加](https://github.com/ca-risken/datasource-api/pull/1/commits/9c9afe5e15418e8639babea6b7e73b203dc5e63c)

2022-06-08 09:42 UTC, mmmknt commented on README.md
> +`RISKEN DataSource API` is a security monitoring system for datasouces(e.g. aws, google, osint..) that searches, analyzes, evaluate, and alerts on discovered threat information.
>security monitoring system for datasouces(e.g. aws, google, osint..) that searches, analyzes, evaluate, and alerts on discovered threat information.

記載されている文章と実際の処理が合っていないです。たとえば、このサービスでは脅威情報の検索や分析、評価、アラートなどは行わないように見えます。

2022-06-08 09:42 UTC, mmmknt commented on README.md
> +`k8s-sample/overlays/local/datasource-api.yaml`
k8s-sampleにこのサービスのマニフェストは見つからなかったです。
後で追加する予定ならTODOなどをつけて未実装であることをわかるようにした方が良いと思います。

2022-06-08 09:42 UTC, mmmknt commented on pkg/server/activity/Makefile
> +####################################################
Makefileが散在していると分かりづらいので、リポジトリのルートに配置されているMakefileにまとめた方がメンテナンスしやすくなると思います

2022-06-08 09:42 UTC, mmmknt commented on main.go
> +	DataKey              string `split_words:"true" required:"true"`                                // code
Code用のパラメータなら`CodeDataKey`とprefixをつけた方が分かりやすくなると思います。

2022-06-08 10:25 UTC, gassara-kys reviewed
activityはデータソースという責務なので、他のデータソース群（guarddutyなど）同様に移行対象から外す
[86410be](https://github.com/ca-risken/datasource-api/pull/1/commits/86410bea28219fac58394de4ffba4d68135a831b)

2022-06-08 10:49 UTC, hnts requested changes

2022-06-08 10:49 UTC, hnts commented on codebuild/multi-arch/buildspec-image.yml
> +      - echo "password ${GITHUB_TOKEN}" >> ~/.netrc
ここはもういらなくなりましたかね？

2022-06-08 10:49 UTC, hnts commented on codebuild/multi-arch/buildspec-manifest.yml
> +      - echo "password ${GITHUB_TOKEN}" >> ~/.netrc
こちらも不要？

2022-06-08 10:49 UTC, hnts commented on main.go
> +	DataKey              string `split_words:"true" required:"true"`                                // code
DataKeyよりも用途がわかる命名ありませんかね？👀

2022-06-08 18:16 UTC, iiiidaaa commented on Dockerfile
> +    PORTSCAN_QUEUE_URL= \
GCPとAWSのPORTSCANで同じQUEUE_URLの変数名が同じになっているので、
AWS_PORTSCAN_QUEUE_URL,GCP_PORTSCAN_QUEUE_URL(GOOGLE_PORTSCAN_QUEUE_URL)のようにプレフィックス付けると良いかと思います。

2022-06-08 18:17 UTC, iiiidaaa commented on Dockerfile
> +    CLOUD_SPLOIT_QUEUE_URL= \
GCPとAWSのPORTSCANで同じQUEUE_URLの変数名が同じになっているので、
AWS_CLOUDSPLOIT_QUEUE_URL,GCP_CLOUDSPLOIT_QUEUE_URL(GOOGLE_CLOUDSPLOIT_QUEUE_URL)のようにプレフィックス付けると良いかと思います。

2022-06-09 01:40 UTC, hnts requested changes

2022-06-09 01:40 UTC, hnts commented on pkg/crypto/crypto.go
> +func DecryptWithBase64(block *cipher.Block, encrypted string) (string, error) {
これは使ってないかもです
gitleaksのscan側で使っているものですね
ここからは削除していいかと！

また、EncryptWithBase64だけがserverのcode packageから呼ばれるのでpackageにしなくてもいいと思います！
server/codeの配下においてよさそうです

2022-06-09 01:40 UTC, hnts commented on pkg/queue/aws.go
> +func (c *Client) sendAWSMessage(ctx context.Context, url string, msg *message.AWSQueueMessage) (*sqs.SendMessageOutput, error) {
sendXXXXMessageは基本同じ内容なので全部1つのメソッドとして書いてもよさそうです

```
func sendMessage(ctx context.Context, url string, msg interface{})
```

gitleaksが引数少し違いますが、gitleaksの改修でfullScanという値は必要なくなるのでいけそうですかね👀

2022-06-09 03:31 UTC, iiiidaaa commented on main.go
> +	AWSPortscanQueueURL              string `split_words:"true" required:"true" default:"http://queue.middleware.svc.cluster.local:9324/queue/aws-portscan"`
default値がどの環境でも使える値なので問題起きていないと思いますが、Dockerfile内のenvで設定されている変数名がPORTSCAN_QUEUE_URLになっているので値を変更したい時に追随できないように見えます。
(Dockerfileの方でも似た指摘をしているのでそちらの修正で良いかと思います。)

2022-06-09 03:33 UTC, iiiidaaa commented on pkg/server/aws/Makefile
> +	grpcurl -plaintext localhost:8081 list datasource.aws.AWSService
ローカルをDocker -> kubernetesに移行した際の修正漏れだと思いますが、grpcurlの向き先を変更してはいかがでしょうか。

2022-06-09 03:39 UTC, iiiidaaa commented on pkg/server/aws/service.go
> +func NewAWSSerevice(repo db.AWSRepoInterface, q queue.AWSQueueAPI, pj project.ProjectServiceClient, l logging.Logger) *AWSService {
typo?
NewAWSSerevice -> NewAWSService

2022-06-09 04:10 UTC, iiiidaaa commented on main.go
> +	GitleaksQueueURL                 string `split_words:"true" default:"http://queue.middleware.svc.cluster.local:9324/queue/code-gitleaks"`
Code,OSINTも他のnamespaaceに合わせてprefixをつけてはいかがでしょうか

2022-06-09 07:09 UTC, mmmknt commented on pkg/message/diagnosis.go
> +package message
他のmessageと同様に、メッセージをパースする関数をこちらに用意した方が見通しが良くなるかと思います。

2022-06-09 07:09 UTC, mmmknt commented on pkg/message/google.go
> +func CutString(input string, cut int) string {
このリポジトリの中で使われていないようですが、外部のリポジトリから呼ばれているのでしょうか？
もし使われているなら、このパッケージには直接関係がない処理なのでそのリポジトリの中に処理を移動した方が良いと思います。

2022-06-09 07:09 UTC, mmmknt commented on pkg/message/google.go
> +func InitScanStatusGCP(g *google.GCPDataSource) *google.AttachGCPDataSourceRequest {
messageに関係ない処理だと思うので、使っているならそこに移動した方が見通しが良くなると思います。

2022-06-09 07:09 UTC, mmmknt commented on pkg/tag/aws.go
> +package tag
pkg/tag配下のコードはこのリポジトリの中の処理と関係ないように思えます。
このリポジトリに移動した意図はなんでしょうか？

2022-06-09 07:09 UTC, mmmknt commented on main.go
> +	db := db.NewClient(dbConf, logger)
変数名がimportしたパッケージと衝突してます

2022-06-09 07:09 UTC, mmmknt commented on main.go
> +	server := server.NewServer(
変数名がimportしたパッケージと衝突してます

2022-06-09 07:09 UTC, mmmknt commented on pkg/queue/sqs.go
> +	session := sqs.New(sess, &aws.Config{
変数名がimportしたパッケージと衝突してます

2022-06-13 02:40 UTC, gassara-kys commented on pkg/server/aws/Makefile
> +	grpcurl -plaintext localhost:8081 list datasource.aws.AWSService
@iiiidaaa ありがとうございます。ローカル開発環境でサンプルリクエストをどのように使っているか、にもよる気がしました。（どこかでMakefileの使い方認識確認して統一した方が良さそうですね。。。。）

@iiiidaaa どのような使い方されてますかね？

例えば私はport-forwarding機能（k9s使ってます）で localhost:8081 経由でgRPCリクエスト送っています。
これだと `make list-service` のようなmakeコマンドが使えるので動作確認が捗りました。

2022-06-13 02:49 UTC, gassara-kys commented on README.md
> +`RISKEN DataSource API` is a security monitoring system for datasouces(e.g. aws, google, osint..) that searches, analyzes, evaluate, and alerts on discovered threat information.
こちら修正しました。
[4741af4](https://github.com/ca-risken/datasource-api/pull/1/commits/4741af484d0ddfd904cc8db5eae8e89df6921c7f)

2022-06-13 02:49 UTC, gassara-kys commented on README.md
> +`k8s-sample/overlays/local/datasource-api.yaml`
こちら修正しました。　[4741af4](https://github.com/ca-risken/datasource-api/pull/1/commits/4741af484d0ddfd904cc8db5eae8e89df6921c7f)

2022-06-13 03:12 UTC, gassara-kys commented on pkg/server/activity/Makefile
> +####################################################
ルートのMakefileに集約してみました [c282f60](https://github.com/ca-risken/datasource-api/pull/1/commits/c282f6091116796f4faa654c2bbc5fffae4c642a)

2022-06-13 03:44 UTC, gassara-kys commented on main.go
> +	DataKey              string `split_words:"true" required:"true"`                                // code
CodeDataKeyに修正しました。 [e2871d6](https://github.com/ca-risken/datasource-api/pull/1/commits/e2871d6d6069bba4781271d45a1f1b393a9e746f)

2022-06-13 03:46 UTC, gassara-kys commented on main.go
> +	DataKey              string `split_words:"true" required:"true"`                                // code
別の指摘でCodeDataKey に変更しました。
もし、なにか良い名前があれば教えてください

2022-06-13 03:50 UTC, gassara-kys commented on codebuild/multi-arch/buildspec-image.yml
> +      - echo "password ${GITHUB_TOKEN}" >> ~/.netrc
ありがとうございます。おっしゃるとおり不要でした。
[6d6ab27](https://github.com/ca-risken/datasource-api/pull/1/commits/6d6ab2718cd1aaa1f1fba1c09a11c46fba87fb41)

2022-06-13 03:50 UTC, gassara-kys commented on codebuild/multi-arch/buildspec-manifest.yml
> +      - echo "password ${GITHUB_TOKEN}" >> ~/.netrc
ありがとうございます。削除しました　[6d6ab27](https://github.com/ca-risken/datasource-api/pull/1/commits/6d6ab2718cd1aaa1f1fba1c09a11c46fba87fb41)

2022-06-13 07:07 UTC, gassara-kys commented on Dockerfile
> +    PORTSCAN_QUEUE_URL= \
キュー名変更しました [4788998](https://github.com/ca-risken/datasource-api/pull/1/commits/4788998d2586a7f4318d0ae7950b65b93456b0b0)

2022-06-13 07:07 UTC, gassara-kys commented on Dockerfile
> +    CLOUD_SPLOIT_QUEUE_URL= \
キュー名変更しました [4788998](https://github.com/ca-risken/datasource-api/pull/1/commits/4788998d2586a7f4318d0ae7950b65b93456b0b0)

2022-06-13 07:07 UTC, gassara-kys commented on main.go
> +	AWSPortscanQueueURL              string `split_words:"true" required:"true" default:"http://queue.middleware.svc.cluster.local:9324/queue/aws-portscan"`
キュー名変更しました [4788998](https://github.com/ca-risken/datasource-api/pull/1/commits/4788998d2586a7f4318d0ae7950b65b93456b0b0)

2022-06-13 07:07 UTC, gassara-kys commented on main.go
> +	GitleaksQueueURL                 string `split_words:"true" default:"http://queue.middleware.svc.cluster.local:9324/queue/code-gitleaks"`
キュー名変更しました [4788998](https://github.com/ca-risken/datasource-api/pull/1/commits/4788998d2586a7f4318d0ae7950b65b93456b0b0)

2022-06-13 07:17 UTC, gassara-kys commented on pkg/crypto/crypto.go
> +func DecryptWithBase64(block *cipher.Block, encrypted string) (string, error) {
cryptoパッケージ削除しました　[f3ad673](https://github.com/ca-risken/datasource-api/pull/1/commits/f3ad67353f6fa7858f8fba38524246f8808c0246)

2022-06-13 07:22 UTC, gassara-kys commented on pkg/server/aws/service.go
> +func NewAWSSerevice(repo db.AWSRepoInterface, q queue.AWSQueueAPI, pj project.ProjectServiceClient, l logging.Logger) *AWSService {
typo 修正しました [3e4448f](https://github.com/ca-risken/datasource-api/pull/1/commits/3e4448f803ef5d5c7baf0fb6358364564ab08f42)

2022-06-13 07:49 UTC, gassara-kys commented on pkg/queue/aws.go
> +func (c *Client) sendAWSMessage(ctx context.Context, url string, msg *message.AWSQueueMessage) (*sqs.SendMessageOutput, error) {
queueパッケージ修正しました。また、gitleaks-full-scanはすでに区別してないということで削除しました。
[40f0264](https://github.com/ca-risken/datasource-api/pull/1/commits/40f0264b018e375b04e3ce2ac7a2c06ec4070433)

2022-06-13 08:01 UTC, gassara-kys commented on pkg/message/diagnosis.go
> +package message
diagnosisのメッセージパース処理追加しました。 [8f7a615](https://github.com/ca-risken/datasource-api/pull/1/commits/8f7a61530f3ab50ab15d25e9e3aa775c4ca83fdb)

2022-06-13 08:08 UTC, gassara-kys commented on pkg/message/google.go
> +func CutString(input string, cut int) string {
message pkgに直接関係のない処理を削除しました [f6e1f05](https://github.com/ca-risken/datasource-api/pull/1/commits/f6e1f05944e7192ee6ed5496fb3f504d09357cc1)

2022-06-13 08:08 UTC, gassara-kys commented on pkg/message/google.go
> +func InitScanStatusGCP(g *google.GCPDataSource) *google.AttachGCPDataSourceRequest {
message pkgに直接関係のない処理を削除しました [f6e1f05](https://github.com/ca-risken/datasource-api/pull/1/commits/f6e1f05944e7192ee6ed5496fb3f504d09357cc1)

2022-06-13 08:10 UTC, gassara-kys commented on pkg/tag/aws.go
> +package tag
おっしゃる通りtag pkgは移す必要ないですね。pkgごと削除しました。
[1864a37](https://github.com/ca-risken/datasource-api/pull/1/commits/1864a37c93c2e9d6302eea5bc2f723f1466c5efb)

2022-06-13 08:17 UTC, gassara-kys commented on main.go
> +	db := db.NewClient(dbConf, logger)
名前の衝突修正しました。 [173785b](https://github.com/ca-risken/datasource-api/pull/1/commits/173785b76ffaa8e1f5a3c143f5c35691cbde5cbc)

2022-06-13 08:17 UTC, gassara-kys commented on main.go
> +	server := server.NewServer(
名前の衝突修正しました。 [173785b](https://github.com/ca-risken/datasource-api/pull/1/commits/173785b76ffaa8e1f5a3c143f5c35691cbde5cbc)

2022-06-13 08:17 UTC, gassara-kys commented on pkg/queue/sqs.go
> +	session := sqs.New(sess, &aws.Config{
名前の衝突修正しました。 [173785b](https://github.com/ca-risken/datasource-api/pull/1/commits/173785b76ffaa8e1f5a3c143f5c35691cbde5cbc)

2022-06-14 01:13 UTC, hnts commented on codebuild/multi-arch/buildspec-batch.yml
> +
空白の2行がありますね！

2022-06-14 01:14 UTC, hnts commented on codebuild/release/buildspec-image.yml
> +      - echo "password ${GITHUB_TOKEN}" >> ~/.netrc
ここももういらない？

2022-06-14 01:14 UTC, hnts commented on codebuild/release/buildspec-manifest.yml
> +      - echo "password ${GITHUB_TOKEN}" >> ~/.netrc
ここももういらない？

2022-06-14 03:11 UTC, gassara-kys commented on codebuild/release/buildspec-image.yml
> +      - echo "password ${GITHUB_TOKEN}" >> ~/.netrc
すいません、確認漏れていました。ありがとうございます。 [220e798](https://github.com/ca-risken/datasource-api/pull/1/commits/220e7980baf586a36bbf6a298b29bf02d5c4b7fd)

2022-06-14 03:11 UTC, gassara-kys commented on codebuild/release/buildspec-manifest.yml
> +      - echo "password ${GITHUB_TOKEN}" >> ~/.netrc
すいません、確認漏れていました。ありがとうございます。 [220e798](https://github.com/ca-risken/datasource-api/pull/1/commits/220e7980baf586a36bbf6a298b29bf02d5c4b7fd)

2022-06-14 03:11 UTC, gassara-kys commented on codebuild/multi-arch/buildspec-batch.yml
> +
修正しました。 [220e798](https://github.com/ca-risken/datasource-api/pull/1/commits/220e7980baf586a36bbf6a298b29bf02d5c4b7fd)

2022-06-14 03:15 UTC, mmmknt commented on README.md
> +`k8s-sample/overlays/local/datasource-api.yaml`
TODOというキーワードをつけて欲しい、ということではなく、現状との差異（と今後の予定）、がドキュメントを読む人に伝わるようにして欲しい、という意図でした。
アプリ自体がk8s-sampleにないなら、Running Appsの記載を`TODO k8s-sampleに追加したら追加`、だけにするといったイメージです。

2022-06-14 03:20 UTC, hnts commented on codebuild/release/buildspec-manifest.yml
> +    GITHUB_TOKEN: '/build/GITHUB_TOKEN'
ここももういらない？

2022-06-14 03:20 UTC, hnts commented on pkg/server/diagnosis/diagnosis_data_source.go
> +func (d *DiagnosisService) ListDiagnosisDataSource(ctx context.Context, req *diagnosis.ListDiagnosisDataSourceRequest) (*diagnosis.ListDiagnosisDataSourceResponse, error) {
少しこのdiagnosis_data_source.goというファイル名は他のservice(awsやgoogleなど)と規則が違うようです

awsはaws.go, googleはgoogle.goのようにdiagnosis.goとしてまとめたほうが一貫性がありそうです(portscan.goなども一緒に)

2022-06-14 03:29 UTC, mmmknt commented on pkg/message/google.go
> +func CutString(input string, cut int) string {
pkg/message/aws.goの`IsMatchAccountIDArn`もmessageに関係ない処理に見えます。こちらもこのパッケージから移動した方が良いのではないでしょうか？

2022-06-14 03:42 UTC, mmmknt commented on Makefile
> +	for svc in "activity"; do \
activityを移動したなら不要？

2022-06-14 04:42 UTC, gassara-kys commented on codebuild/release/buildspec-manifest.yml
> +    GITHUB_TOKEN: '/build/GITHUB_TOKEN'
[220e798](https://github.com/ca-risken/datasource-api/pull/1/commits/220e7980baf586a36bbf6a298b29bf02d5c4b7fd)で修正済みです:pray:

2022-06-14 04:49 UTC, gassara-kys commented on pkg/server/diagnosis/diagnosis_data_source.go
> +func (d *DiagnosisService) ListDiagnosisDataSource(ctx context.Context, req *diagnosis.ListDiagnosisDataSourceRequest) (*diagnosis.ListDiagnosisDataSourceResponse, error) {
diagnosis_data_source.go -> diagnosis.go  に修正してみました。

> portscan.goなども一緒に

こちらは、もともと各スキャンでファイルが分かれていたのは分割の粒度はそのままにしています。（名前はスキャン名にあわせました）
- applicationscan
- wpscan
- portscan

[e9d4a67](https://github.com/ca-risken/datasource-api/pull/1/commits/e9d4a67fbc867759d64e74364debef2c00416697)

2022-06-14 04:55 UTC, gassara-kys commented on Makefile
> +	for svc in "activity"; do \
ありがとうございます、消し忘れでした。。。
[f1be16c](https://github.com/ca-risken/datasource-api/pull/1/commits/f1be16cc4e54a95083d5ca2cc2746755d296f899)

2022-06-14 04:59 UTC, gassara-kys commented on README.md
> +`k8s-sample/overlays/local/datasource-api.yaml`
ありがとうございます。意図理解しました。修正してみましたが、問題ないでしょうか、、、？
[1d5cd60](https://github.com/ca-risken/datasource-api/pull/1/commits/1d5cd60a83deac17d1ef20fa759f96d393329c6b)

2022-06-14 04:59 UTC, hnts commented on pkg/server/diagnosis/diagnosis_data_source.go
> +func (d *DiagnosisService) ListDiagnosisDataSource(ctx context.Context, req *diagnosis.ListDiagnosisDataSourceRequest) (*diagnosis.ListDiagnosisDataSourceResponse, error) {
scan.goはdiagnosis.goに統合してよさそうでう

2022-06-14 05:02 UTC, gassara-kys commented on pkg/message/google.go
> +func CutString(input string, cut int) string {
ありがとうございます。こちらも削除しました。パッケージに無関係かつスキャナ側で利用してたものでした。
[9cab1c6](https://github.com/ca-risken/datasource-api/pull/1/commits/9cab1c62bb8399ef31662c6f73f551e365160512)

2022-06-14 05:32 UTC, hnts approved these changes

2022-06-14 06:04 UTC, mmmknt commented on README.md
> +`k8s-sample/overlays/local/datasource-api.yaml`
対応ありがとうございます！完璧な記載だと思います！

2022-06-14 06:04 UTC, mmmknt approved these changes
LGTM!

2022-06-14 06:08 UTC, gassara-kys commented on pkg/server/diagnosis/diagnosis_data_source.go
> +func (d *DiagnosisService) ListDiagnosisDataSource(ctx context.Context, req *diagnosis.ListDiagnosisDataSourceRequest) (*diagnosis.ListDiagnosisDataSourceResponse, error) {
scan.go 統合しました。
[59c1aa7](https://github.com/ca-risken/datasource-api/pull/1/commits/59c1aa7f272faa957013da19ea5277f8d93c8da8)

2022-06-14 06:26 UTC, iiiidaaa approved these changes

2022-06-14 06:33 UTC, merged